### ISSUE TITLE
Did somebody try to rebuild it in europe?

### ISSUE THREAD

**Issue by DominicBoettger** [MGX3D/Turntable#2]
As there are lot of products not available in the "metric" world. I asked myself if somebody found suitable products and dimension for the rest of the world.

**Comment by MGX3D** [comment]
Most of the parts are in the metric system, a few that have escaped are not at all critical to the design or function. For example the extrusion or screws - replace them with similarly sized metric parts, the design is simple enough to scale and flexible enough to adjust over wide ranges (example belt size, extrusion size, etc).

**Comment by DominicBoettger** [comment]
Thanks a lot. I will have a look for a similar Aluminium extrusion. I will try it.

**Comment by ashenkin** [comment]
Hey @DominicBoettger , I'm in the UK, and interested in building one too. Wondering if you found the parts in europe? thanks...
