### ISSUE TITLE
Steppermotor - Hardware

### ISSUE THREAD

**Issue by sjeesflix** [MGX3D/Turntable#3]
Hello,

Im trying to replicate the project you did, but I don't have a lot of experience with electronics and programming. In the code you provide, you adres 5 pins for configuration for the teensy 2.0. I guess stepPin goes into PUL, enblPin goes into ENBL and dirPin goes into DIR from the DM420A? This leaves me with 2 pins: readoutPin and triggerPin. 

With pinMode(readoutPin, INPUT); you set this pin to input and with pinMode(triggerPin, INPUT_PULLUP); you set this pin to input as well, only with a pull up resistor

I don't really know what to do with these pins. Obviously I should implement some kind of button/switch, but I don't know how? Can you please provide me with some information?

Thanks in advance!! 

PS: Nice project! very cool

**Comment by MGX3D** [comment]
triggerPin is a NC (normally closed) switch, this is to trigger a rotation on click (or step-by-step if you keep it pressed). GPIO1 is right next to GND on ESP8266, so you can just solder a microswitch in place there.
readoutPin was reserved for a sensor, but is not used anywhere, ignore it.
