### ISSUE TITLE
RaspPi for photogrammetry automation

### ISSUE THREAD

**Issue by ashenkin** [MGX3D/Turntable#4]
Thanks so much for this great writeup.  I'm interested in putting together a system to automate photogrammetry.  So, the idea would be to program the system to rotate x degrees, then trigger a camera, then rotate again, another photo, etc.  I suspect that a raspberry pi (or laptop) might be a bit more flexible than an arduino in terms of making complex automation happen.  I'm wondering if you might have any thoughts about this?  Think the arduino would be replaced by the rpi, or perhaps just have the rpi controlling the arduino?

thanks again...

**Comment by MGX3D** [comment]
Definitely possible to use raspberry pi just by itself to control the stepper as well as add additional stuff, I didn't have time to try it myself but it should work. In fact, for a newer version of this (which I haven't published yet) I've used an ESP8266 to expose: 
- REST APIs over WiFi and equivalent USB commands for low latency stepping
- stepper control
- a line laser on/off
all in one $7 board (no Arduino/Teensy). ESP32 would make it even more interesting (BlueTooth, etc).

**Comment by ashenkin** [comment]
Very slick.  Thanks for the info - i'll ping you if i end up implementing this!
