### ISSUE TITLE
stepper model

### ISSUE THREAD

**Issue by ashenkin** [MGX3D/Turntable#5]
hi there,
i'm having an issue finding an NMEA 23 stepper with the specified torque that comes in under the 2A that the DM420A driver can handle.  Wondering if you might share the specific stepper you used?  I'll look for the alternative driver you spec'd, but still curious about the stepper model...  Thanks...

**Comment by MGX3D** [comment]
Specific model I used Wantai 57BYGH115-003, but many others work here. 
Note: The stepper should have higher current rating than the driver, and note DM420A as peak 2.83A.

**Comment by ashenkin** [comment]
Thanks for the reply.  I picked up a Motech MT-2315HS300AW (http://www.motechmotor.com/products_detail.php?id=159&cid=&page=3), 3A/phase.  The HY-DIV268N-5A is more readily available than the DM420A here.  Do you think its 5A rating would make it risky to use with a stepper rated to 3A?  I can sniff around for other options if so...

**Comment by ashenkin** [comment]
nevermind - i see there are dip switches for the current.  anyway, i'm picking up a TB6600 as they're readily available here... will try to update with a parts list from europe once i've built and tested...
